{{- if and .Values.podDisruptionBudget.enabled (gt (int .Values.web.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kestrel.fullname" . }}-web
  labels:
    {{- include "kestrel.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "kestrel.web.selectorLabels" . | nindent 6 }}
{{- end }}
