apiVersion: v1
kind: Service
metadata:
  name: {{ include "kestrel.fullname" . }}-web
  labels:
    {{- include "kestrel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "kestrel.web.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
